// <auto-generated />
using System;
using AcademicDisciplinesGA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicDisciplinesGA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240829183123_AddMoreCoursesAndCompetences")]
    partial class AddMoreCoursesAndCompetences
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Chair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Chairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyId = 1,
                            Title = "Department of Computer Technologies"
                        },
                        new
                        {
                            Id = 2,
                            FacultyId = 2,
                            Title = "Department of Theoretical Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 3,
                            Title = "Department of Quantum Mechanics"
                        },
                        new
                        {
                            Id = 4,
                            FacultyId = 4,
                            Title = "Department of Organic Chemistry"
                        });
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Competences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMandatory = true,
                            Name = "Programming Basics"
                        },
                        new
                        {
                            Id = 2,
                            IsMandatory = true,
                            Name = "Object-Oriented Design"
                        },
                        new
                        {
                            Id = 3,
                            IsMandatory = true,
                            Name = "Data Structures and Algorithms"
                        },
                        new
                        {
                            Id = 4,
                            IsMandatory = true,
                            Name = "Software Engineering Principles"
                        },
                        new
                        {
                            Id = 5,
                            IsMandatory = true,
                            Name = "Database Systems"
                        },
                        new
                        {
                            Id = 6,
                            IsMandatory = true,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 7,
                            IsMandatory = false,
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = 8,
                            IsMandatory = true,
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = 9,
                            IsMandatory = false,
                            Name = "Computer Vision"
                        },
                        new
                        {
                            Id = 10,
                            IsMandatory = true,
                            Name = "Biostatistics"
                        },
                        new
                        {
                            Id = 11,
                            IsMandatory = false,
                            Name = "Cryptology"
                        },
                        new
                        {
                            Id = 12,
                            IsMandatory = true,
                            Name = "Quantum Computing"
                        },
                        new
                        {
                            Id = 13,
                            IsMandatory = false,
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 14,
                            IsMandatory = true,
                            Name = "Ethical Hacking"
                        },
                        new
                        {
                            Id = 15,
                            IsMandatory = false,
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 16,
                            IsMandatory = true,
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 17,
                            IsMandatory = true,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 18,
                            IsMandatory = false,
                            Name = "Mobile App Development"
                        });
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChairId")
                        .HasColumnType("int");

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChairId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 1,
                            Title = "Intro to Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            ChairId = 1,
                            ECTS = 6,
                            TeacherId = 2,
                            Title = "Advanced Programming"
                        },
                        new
                        {
                            Id = 3,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 3,
                            Title = "Algorithms and Data Structures"
                        },
                        new
                        {
                            Id = 4,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 4,
                            Title = "Software Engineering"
                        },
                        new
                        {
                            Id = 5,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 5,
                            Title = "Databases 101"
                        },
                        new
                        {
                            Id = 6,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 6,
                            Title = "Web Development Fundamentals"
                        },
                        new
                        {
                            Id = 7,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 7,
                            Title = "Frontend Web Development"
                        },
                        new
                        {
                            Id = 8,
                            ChairId = 1,
                            ECTS = 6,
                            TeacherId = 8,
                            Title = "Backend Web Development"
                        },
                        new
                        {
                            Id = 9,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 9,
                            Title = "Computer Vision Basics"
                        },
                        new
                        {
                            Id = 10,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 10,
                            Title = "Biostatistics 101"
                        },
                        new
                        {
                            Id = 11,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 1,
                            Title = "Introduction to Cryptology"
                        },
                        new
                        {
                            Id = 12,
                            ChairId = 1,
                            ECTS = 6,
                            TeacherId = 2,
                            Title = "Quantum Computing Fundamentals"
                        },
                        new
                        {
                            Id = 13,
                            ChairId = 1,
                            ECTS = 4,
                            TeacherId = 3,
                            Title = "Networking Fundamentals"
                        },
                        new
                        {
                            Id = 14,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 4,
                            Title = "Introduction to Ethical Hacking"
                        },
                        new
                        {
                            Id = 15,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 5,
                            Title = "Cloud Computing Basics"
                        },
                        new
                        {
                            Id = 16,
                            ChairId = 1,
                            ECTS = 6,
                            TeacherId = 6,
                            Title = "Game Development Basics"
                        },
                        new
                        {
                            Id = 17,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 7,
                            Title = "Introduction to AI"
                        },
                        new
                        {
                            Id = 18,
                            ChairId = 1,
                            ECTS = 5,
                            TeacherId = 8,
                            Title = "Mobile App Development 101"
                        });
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.CourseCompetence", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "CompetenceId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("CourseCompetence");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CompetenceId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            CompetenceId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            CompetenceId = 3
                        },
                        new
                        {
                            CourseId = 4,
                            CompetenceId = 4
                        },
                        new
                        {
                            CourseId = 5,
                            CompetenceId = 5
                        },
                        new
                        {
                            CourseId = 6,
                            CompetenceId = 6
                        },
                        new
                        {
                            CourseId = 7,
                            CompetenceId = 7
                        },
                        new
                        {
                            CourseId = 8,
                            CompetenceId = 8
                        },
                        new
                        {
                            CourseId = 9,
                            CompetenceId = 9
                        },
                        new
                        {
                            CourseId = 10,
                            CompetenceId = 10
                        },
                        new
                        {
                            CourseId = 11,
                            CompetenceId = 11
                        },
                        new
                        {
                            CourseId = 12,
                            CompetenceId = 12
                        },
                        new
                        {
                            CourseId = 13,
                            CompetenceId = 13
                        },
                        new
                        {
                            CourseId = 14,
                            CompetenceId = 14
                        },
                        new
                        {
                            CourseId = 15,
                            CompetenceId = 15
                        },
                        new
                        {
                            CourseId = 16,
                            CompetenceId = 16
                        },
                        new
                        {
                            CourseId = 17,
                            CompetenceId = 17
                        },
                        new
                        {
                            CourseId = 18,
                            CompetenceId = 18
                        });
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "PrerequisiteId");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("CoursePrerequisite");

                    b.HasData(
                        new
                        {
                            CourseId = 2,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 3,
                            PrerequisiteId = 2
                        },
                        new
                        {
                            CourseId = 4,
                            PrerequisiteId = 3
                        },
                        new
                        {
                            CourseId = 5,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 6,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 8,
                            PrerequisiteId = 7
                        },
                        new
                        {
                            CourseId = 9,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 10,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 11,
                            PrerequisiteId = 5
                        },
                        new
                        {
                            CourseId = 12,
                            PrerequisiteId = 3
                        },
                        new
                        {
                            CourseId = 13,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 14,
                            PrerequisiteId = 6
                        },
                        new
                        {
                            CourseId = 15,
                            PrerequisiteId = 3
                        },
                        new
                        {
                            CourseId = 16,
                            PrerequisiteId = 17
                        },
                        new
                        {
                            CourseId = 17,
                            PrerequisiteId = 8
                        },
                        new
                        {
                            CourseId = 18,
                            PrerequisiteId = 7
                        });
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Faculty of Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Faculty of Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Faculty of Physics"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Faculty of Chemistry"
                        });
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dr. Emily Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Prof. Mark Brown"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dr. Susan Clark"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Prof. Joseph Davis"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dr. Karen Wilson"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Prof. Christopher Taylor"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dr. Daniel Moore"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Prof. Laura Thompson"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dr. Patricia White"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Prof. Sarah Harris"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int?>("ChairId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ChairId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Chair", b =>
                {
                    b.HasOne("AcademicDisciplinesGA.Models.Faculty", "Faculty")
                        .WithMany("Chairs")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Competence", b =>
                {
                    b.HasOne("AcademicDisciplinesGA.Models.ApplicationUser", null)
                        .WithMany("Competences")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Course", b =>
                {
                    b.HasOne("AcademicDisciplinesGA.Models.Chair", "Chair")
                        .WithMany()
                        .HasForeignKey("ChairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicDisciplinesGA.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chair");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.CourseCompetence", b =>
                {
                    b.HasOne("AcademicDisciplinesGA.Models.Competence", "Competence")
                        .WithMany()
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicDisciplinesGA.Models.Course", "Course")
                        .WithMany("Competences")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("AcademicDisciplinesGA.Models.Course", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademicDisciplinesGA.Models.Course", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.ApplicationUser", b =>
                {
                    b.HasOne("AcademicDisciplinesGA.Models.Chair", "Chair")
                        .WithMany()
                        .HasForeignKey("ChairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chair");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Course", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Faculty", b =>
                {
                    b.Navigation("Chairs");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("AcademicDisciplinesGA.Models.ApplicationUser", b =>
                {
                    b.Navigation("Competences");
                });
#pragma warning restore 612, 618
        }
    }
}
